
services:
  nginx:
    build: 
      context: ./
      dockerfile: nginx.dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ../src:/var/www/html/
    depends_on:
      - php

  php:
    build: 
      context: ./
      dockerfile: php.dockerfile
    expose:
      - 9000
    volumes:
      - ../src:/var/www/html/

  composer:
    image: composer
    volumes: 
      - ../src:/var/www/html/
    entrypoint: ['composer']
    working_dir: /var/www/html/

  node:
    image: node
    volumes: 
      - ../src:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: ['npm','run','build']

  npm:
    image: node
    volumes: 
      - ../src:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: ['npm']
    
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'local'
      MYSQL_PASSWORD: 'secret'      
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - ./mysql:/var/lib/mysql 
